language: java
sudo: false
jdk: oraclejdk8
dist: trusty

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/.sonar/cache

addons:
    sonarcloud:
        organization: "olszewskimichal-github"
        token:
          secure: ${SONAR_TOKEN}
jobs:
  include:
    - stage: test
      script:
        - mvn test sonar:sonar -B
      after_success:
       - bash <(curl -s https://codecov.io/bash)