language: java
sudo: false
jdk: oraclejdk8
dist: trusty

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/.sonar/cache

addons:
    sonarcloud:
        organization: "olszewskimichal-github"
        token:
          secure: ${SONAR_TOKEN}
        branches:
          - master
          - develop
script:
    - sonar-scanner

jobs:
  include:
    - stage: test
      script:
        - mvn test sonar:sonar -Dsonar.coverage.exclusions=**/pl/michal/olszewski/rssaggregator/config/** -B
      after_success:
       - bash <(curl -s https://codecov.io/bash)