language: java
sudo: false
jdk: oraclejdk8
dist: trusty

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/.sonar/cache

addons:
    sonarcloud:
        organization: "testtravis"
        token:
          secure: ${SONAR_TOKEN}
jobs:
  include:
    - stage: unit
      script:
        - mvn test -P unit-testing -B
    - stage: integration
      script:
        - mvn test -P integration-testing -B
    - stage: sonar
      script:
        - mvn org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar
      after_success:
       - bash <(curl -s https://codecov.io/bash)
